### ISSUE TITLE
Crash on Forge 2151

### ISSUE THREAD

**Issue by skruis** [lumien231/Bloodmoon#12]
Receiving a crash on my server every night. I had set the Blood Moon to trigger on every full moon. I've just disabled this and am testing again.

Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.World.func_72853_d()I
	at lumien.bloodmoon.server.BloodmoonHandler.endWorldTick(BloodmoonHandler.java:96)
	at lumien.bloodmoon.handler.BloodmoonEventHandler.endWorldTick(BloodmoonEventHandler.java:114)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_204_BloodmoonEventHandler_endWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

[crash-2016-12-01_10.16.44-server.txt](https://github.com/lumien231/Bloodmoon/files/625159/crash-2016-12-01_10.16.44-server.txt)

**Comment by lumien231** [comment]
Can you reproduce this without any other mods installed?

**Comment by skruis** [comment]
I'll try and let you know -but- I've reset the full moon option back to off and I haven't seen a crash yet.

**Comment by skruis** [comment]
Still have not tried without any mods but I did disable the blood moon on every full moon feature and it has not crashed and I have gone through several blood moons. It seems to be specific to the full moon feature.
