### ISSUE TITLE
missing plugin.yml?

### ISSUE THREAD

**Issue by happydrgn** [lumien231/Bloodmoon#3]
I opened the jar and couldn't find a plugin.yml file in the top level of the jar. Here's the corresponding bukkit error. 

[12:28:56 ERROR]: Could not load 'plugins/Bloodmoon-1.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.8.3.jar:git-Spigot-2f787bd-a5b7881]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.3.jar:git-Spigot-2f787bd-a5b7881]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.3.jar:git-Spigot-2f787bd-a5b7881]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [spigot-1.8.3.jar:git-Spigot-2f787bd-a5b7881]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.3.jar:git-Spigot-2f787bd-a5b7881]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by lumien231** [comment]
It's not a plugin? It's a Forge Mod.
